package io.github.tbondetti.authserver.core.exception;

public enum AuthServerErrorCode {
    USER_NOT_FOUND,
    USERNAME_IS_REQUIRED,
    USERNAME_IS_TOO_LONG,
    USERNAME_ALREADY_EXISTS,
    PASSWORD_IS_REQUIRED,
    PASSWORD_IS_TOO_SHORT,
    PASSWORD_IS_TOO_LONG,

    CODE_IS_REQUIRED,
    CODE_IS_TOO_LONG,
    DESCRIPTION_IS_TOO_LONG,

    NAME_IS_REQUIRED,
    NAME_IS_TOO_LONG,

    APPLICATION_NOT_FOUND,
    APPLICATION_CODE_ALREADY_EXISTS,

    ROLE_NOT_FOUND,
    ROLE_CODE_ALREADY_EXISTS,
    ROLE_ALREADY_ASSIGNED,

    ACCESS_DENIED,
    INVALID_CREDENTIALS,
    ACCOUNT_DISABLED,
}
