@startuml
title Architecture modulaire

skinparam shadowing false
skinparam roundcorner 10

rectangle "auth-server-core" as core

rectangle "auth-server-application" as application
rectangle "auth-server-web" as web

rectangle "auth-server-persistence" as persistence
rectangle "auth-server-security" as security

rectangle "auth-server-boot" as boot

web --> application
application --> core

persistence --> core
security --> core

boot --> web
boot --> persistence
boot --> security

@enduml