env.spring.datasource.url=jdbc:postgresql://localhost:5432/local
env.spring.datasource.username=admin
env.spring.datasource.password=admin

env.spring.jpa.show-sql=true

env.test-resource-server.url=http://localhost:8081

env.springdoc.api-docs.enabled=true
env.springdoc.swagger-ui.enabled=true

env.logging.level.org.springframework.security=TRACE