name: Build and Sonar

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build, test and generate coverage
        run: mvn clean verify

      - name: Sonar analysis
        if: github.actor != 'dependabot[bot]'
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
