name: Build and Sonar

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
          cache: maven

      - name: Build, test and generate coverage
        run: mvn clean verify

      - name: Sonar scan
        run: >
          mvn sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=thibaultcgi
          -Dsonar.projectKey=ThibaultCGI_auth-server
          -Dsonar.coverage.jacoco.aggregateXmlReportPaths=auth-coverage-report/target/site/jacoco-aggregate/jacoco.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
